// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerSearch': string;
  'input': string;
  'show': string;
}
declare const cssExports: CssExports;
export = cssExports;
