// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'appHeader': string;
  'appLink': string;
  'appLogo': string;
}
declare const cssExports: CssExports;
export = cssExports;
