// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'action': string;
  'avatar': string;
  'dark': string;
  'logo': string;
  'menu': string;
  'name': string;
  'right': string;
  'search': string;
  'trigger': string;
}
declare const cssExports: CssExports;
export = cssExports;
